### ISSUE TITLE
Update Work Order

### ISSUE THREAD

**Issue by matthewtsmith** [apptreesoftware/corrigo-issues#3]
- [x] Reassign Work Orders: https://github.com/apptreesoftware/corrigo-issues/issues/2
- [x] Update Work Order Status: https://github.com/apptreesoftware/corrigo-issues/issues/4
- [x] Add a note: https://github.com/apptreesoftware/corrigo-issues/issues/5
- [ ] Add attachment: https://github.com/apptreesoftware/corrigo-issues/issues/6
- [x] Close work order: https://github.com/apptreesoftware/corrigo-issues/issues/7
- [x] Flag Work Order: https://github.com/apptreesoftware/corrigo-issues/issues/8

**Comment by SamOrozco** [comment]
Should users only be able to update work orders assigned to them?

**Comment by matthewtsmith** [comment]
@SamOrozco Yes, lets allow allow editing on WO's assigned to the logged in user.

**Comment by SamOrozco** [comment]
This is completed in preview-baptisthealth.corrigo.com beta. There is no Update Work Orders option. They are able to update their own work orders that show up in "my work orders" or if they search for work orders and they are theirs they can edit.
